sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

cache:
  yarn: true
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp-cli
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
    - yarn build --p
