sudo: false
language: php
php:
  - 5.6
  - 5.5
  - 5.4

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp
  - npm install
  - bower install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

# script:
#   - npm run build
#   - npm run jshint
#   - npm run jscs
#   - phpcs --standard=ruleset.xml --extensions=php -n -s .
